AWSTemplateFormatVersion: 2010-09-09
Description: <?app-name> - Storage Postgres

Parameters:
  Env:
    Type: String
  DBName:
    Type: String
    Default: <?app-name>-rds
  ProdDbClusterTimeout:
    Type: Number

Conditions:
  IsProdEnv: !Equals
    - !Ref Env
    - 'prod'

Resources:
  <?db-subnet-group>

  DatabaseCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      BackupRetentionPeriod: 35
      DatabaseName: !Join [ '', !Split [ '-', !Ref DBName ] ]
      <?db-subnet-group-name>
      DeletionProtection: true
      Engine: aurora-postgresql
      EngineMode: serverless
      EngineVersion: 13.9 #Only postgresql version 13.9 and 11.9 supports Aurora serverless v1
      MasterUsername: !Sub '{{resolve:ssm:/<?app-name>/${Env}/db/username}}'
      MasterUserPassword: !Sub '{{resolve:ssm:/<?app-name>/${Env}/db/password}}'
      <?db-sg-ids>
      ScalingConfiguration:
        SecondsUntilAutoPause:
          !If [ IsProdEnv,  !Ref ProdDbClusterTimeout, 300 ]


  DatabaseClusterSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join [ '', [ /<?app-name>/, !Ref Env, /db/url ] ]
      Type: String
      Value:
        Fn::Join:
          - ''
          - - jdbc:postgresql://
            - Fn::GetAtt:
                - DatabaseCluster
                - Endpoint.Address
            - ':'
            - Fn::GetAtt:
                - DatabaseCluster
                - Endpoint.Port
            - '/'
            - !Join [ '', !Split [ '-', !Ref DBName ] ]

  DatabaseClusterIdentifierSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join [ '', [ /<?app-name>/, !Ref Env, /db/identifier ] ]
      Type: String
      Value: !GetAtt DatabaseCluster.Endpoint.Address

Outputs:
  DatabaseClusterSSM:
    Value: !GetAtt DatabaseClusterSSM.Value