name: Release to artifactory

on:
  workflow_dispatch:

jobs:
  release-version:
    uses: ./.github/worflows/release-version.yml
    secrets: inherit

  release-to-artifactory:
    runs-on: ubuntu-latest

    needs: release-version

    env:
      semver: ${{ needs.release-version.outputs.semver }}

    steps:
      ###############################################################
      ########## GENERATE AND PUBLISH TYPESCRIPT CLIENT #############
      ###############################################################

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Generate typescript client
        run: ./gradlew generateReactClient -Pargs=${{ env.semver }}

      - name: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1.0.3
        with:
          version: 2
          verbose: false
          arch: amd64
          rootdir: ''
          workdir: ''
      - name: Connect to AWS
        run: |
          sh ./.shell/initAWS.sh ${{ secrets.PREPROD_AWS_ACCESS_KEY_ID }} ${{ secrets.PREPROD_AWS_SECRET_ACCESS_KEY }} ${{ secrets.AWS_REGION }}
          sh ./.shell/initNpmrc.sh bpartners-store npm-bpartners-app 688605879718 eu-west-3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 17.x

      - name: Publish React client
        run: |
          cd build/gen-react-client/
          sed -i "s/\"https:\/\/api-dev.bpartners.app\"/\(process.env.REACT_APP_BPARTNERS_API_URL || \"\"\)/g" base.ts
          sed -i "s/\"dependencies\"/\"peerDependencies\"/g" package.json
          sed -i '11d' tsconfig.json && sed -i "s/\"es6\",/\"es6\"/g" tsconfig.json
          echo -e "\n*.ts\nnode_module\n!*.d.ts\n.idea\n.vscode\n.openapi-generator\n.openapi-generator-ignore\ngit_push.sh" >> .npmignore
          npm config set always-auth true
          npm install
          npm publish